<br><br><br><br><br><br>
<div style="margin-left: 250px; margin-right: 250px; margin-bottom: 30px;">
    <img src="<?php echo $this->baseUrl('img/check.png'); ?>" style="float:left;"> 
    <br>
    <h4 style="float: left; margin-left: 30px;">Ogłoszenie usunięte, powrót do <a href="<?php echo $this -> url(array('controller' => 'index', 'action' => 'index' ), null, true)?>"><b>strony głównej.</b></a></h4>
</div>