<div class="b-cont mar40p">
<?php if($this->object['status'] != 0): ?>
<?php echo $this->form ?>
<p>
                            <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['ad_id'])) ?>">
                                <button class="btn btn-danger w87p">Edytuj</button>
                            </a>
</p>
</div>>
<?php else: ?>
    <p class="b-cont mar40p fs20p"><strong>Ogłoszenie wygasło</strong></p>
<?php endif; ?>