<?php $this->headTitle('Strona główna'); ?>

<p class="lead" style="color: #3a87ad; text-decoration: underline">
    <strong>Najnowsze ogłoszenia</strong>
<?php foreach($this->ads as $ad): ?>
<div class="br20 bg-c4 pad10p martb10p">
    <div class="bg-c2 mar10p fs20p pad20p bs5 br20 fw-b"><a href="#"><?php echo $ad['topic'] ?></a></div>
    <div class="pad20p mar10p  bg-c1 bs5 br10"><?php echo $ad['content'] ?></div> <!-- treść ogłoszenia -->
    <div class="padlr20p bg-c2 mar10p br10"><?php echo $ad['datetime'] ?></div> <!-- data zamieszczenia-->
    <!-- poniżej blok operacji -->
    <div class="mar10p">
        <a href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>">
            <button>szczegóły</button></a>
        <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $ad['ad_id'])) ?>">
            <button>edytuj</button></a>
        <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $ad['ad_id'])) ?>">
            <button>usuń</button></a>
    </div>
</div>
<?php endforeach; ?>

<a href="<?php echo $this->url(array('action' => 'createform'))
        ?>"><button>Dodaj nowy rekord</button></a>
</p> 