<?php $this->headTitle('Strona główna'); ?>
<?php /* --- bootstrap banner carousel --- */ ?>
<?php /*
<div class="t-ac pad" style="padding-top: 20px">
<div id="carousel-wmi-captions" class="carousel slide mara" data-ride="carousel" style="width: 900px; height: 165px">
  <!-- Indicators -->
 */ ?>
 <?php /* --- kropeczki, których Leszek nie chce ;) ---*/
 
 
  /*
  <ol class="carousel-indicators">
    <li data-target="#carousel-wmi-captions" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-wmi-captions" data-slide-to="1"></li>
    <li data-target="#carousel-wmi-captions" data-slide-to="2"></li>
  </ol>
*/ 
  ?>
  <?php /*
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
      <?php        foreach ($this->slideshow as $k => $s){ ?>
    <div class="item <?php if ($k==0) echo "active"; ?> bg-c<?php echo rand(1,6); ?>">
   */ ?>
        <?php /* --- tło w postaci grafiki --- */ ?>
        <?php /*
        <img class="" src="<?php echo $this->baseUrl(); ?>/img/overlay.png" alt="">
      <div class="carousel-caption t0">
          <h1 class="mart47p"><a class="d-b w100 h100 p-a fc-f hov" href="<?php echo $this->url(array('action' => 'show', 'id' => $s['ad_id'])) ?>"><?php if (strlen($s['topic']) <=31){
                   echo $s['topic'];
                }else {
                   echo $string2 = substr($s['topic'], 0, 31);echo'(...)';
                } ?></a></h1>

      </div>
    </div>
      <?php } ?>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-wmi-captions" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-wmi-captions" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
</div>
         *  */ ?>
        
<?php /* --- carousel stop --- */ ?>
<?php /* --- layout indexu --- */ ?>
<hr> 
<?php /* --- przestarzałe ---
<h3>Ogłoszenia pracowników</h3>
<hr>
<?php foreach($this->faculty_ads as $ad): ?>
<div class="h360p w40 fl p-r mar5 bgo clearDeco oh fc-f bg-c<?php echo rand(1,6); ?>">
    <a class="d-b w100 h100 p-a fc-f" href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>">
        <div class="padlr20p">
            <h4><?php echo $ad['topic'] ?></h4>
            <p><?php echo $ad['content'] ?></p>
        </div>
    </a>
    <div class="bg-r3 p-a b-100 fc-f w100 ad-panel an">
        <span class="d-ib pad10p fl">Autor: <?php echo $ad['username'] ?></span>
        <span class="d-ib pad10p fl"><?php echo $ad['datetime'] ?></span>
    <?php if($this->identity): ?>
        <?php if($this->identity->user_id == $ad['author']): ?>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" href="<?php echo $this->url(array('action' => 'edit', 'id' => $ad['ad_id'])) ?>">Edytuj</a>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" href="<?php echo $this->url(array('action' => 'delete', 'id' => $ad['ad_id'])) ?>">Usuń</a>
        <?php endif; ?>
    <?php endif; ?>
    </div>
</div>
<?php endforeach; ?>
<?php if($this->faculty_nr_per_page<$this->faculty_count){ ?>
<div class="clf ta-c">
    <p class="padlr30p b3psr3 clearDeco d-ib bg-r3 fc-f fw-b">
    <?php 
    if(intval($this->students_page)>1) $url_array['up']=$this->students_page;
    if ($this->faculty_page!=1){
    ?>
        <a class="fc-f marlr6p" href="<?php $url_array['ep']=$this->faculty_page-1; echo $this->url($url_array); ?>" >&lt;&lt;</a>
    <?php
    }
    for ($index = 1; $index <= $this->faculty_pages; $index++) { 
        if($index==$this->faculty_page){ ?>
        <span class="fc-f padlr6p bg-r3"><?php echo $index; ?></span>
        <?php }else{
       $url_array['ep']=$index;
        ?>
    <a class="fc-f marlr6p" href="<?php echo $this->url($url_array); ?>"><?php echo $index; ?></a>
        <?php }
        } if ($this->faculty_page!=$this->faculty_pages){
    ?>
    <a class="fc-f marlr6p" href="<?php $url_array['ep']=$this->faculty_page+1; echo $this->url($url_array); ?>" >&gt;&gt;</a>
    <?php
    } ?>
    </p>
</div>
<hr>
<?php }else{ ?>
<hr class="clf">
<?php }?>
<h3>Ogłoszenia studentów</h3>
<hr>
<?php foreach($this->students_ads as $ad): ?>
<div class="h360p w40 fl p-r mar5 bgo clearDeco oh fc-f bg-c<?php echo rand(1,6); ?>">
    <a class="d-b w100 h100 p-a fc-f" href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>">
        <div class="padlr20p">
            <h4><?php echo $ad['topic'] ?></h4>
            <p><?php echo $ad['content'] ?></p>
        </div>
    </a>
    <div class="bg-r3 p-a b-100 fc-f w100 ad-panel an">
        <span class="d-ib pad10p fl">Autor: <?php echo $ad['username'] ?></span>
        <span class="d-ib pad10p fl"><?php echo $ad['datetime'] ?></span>
    <?php if($this->identity): ?>
        <?php if($this->identity->user_id == $ad['author']): ?>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" href="<?php echo $this->url(array('action' => 'edit', 'id' => $ad['ad_id'])) ?>">Edytuj</a>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" href="<?php echo $this->url(array('action' => 'delete', 'id' => $ad['ad_id'])) ?>">Usuń</a>
        <?php endif; ?>
    <?php endif; ?>      
    </div>
</div>
<?php endforeach; ?>
<?php if($this->students_nr_per_page<$this->students_count){ ?>
<div class="clf ta-c">
    <p class="padlr30p b3psr3 clearDeco d-ib bg-r3 fc-f fw-b">
    <?php 
    if(intval($this->faculty_page)>1) $url_array['ep']=$this->faculty_page;
    if ($this->students_page!=1){
    ?>
        <a class="fc-f marlr6p" href="<?php $url_array['up']=$this->students_page-1; echo $this->url($url_array); ?>" >&lt;&lt;</a>
    <?php
    }
    for ($index = 1; $index <= $this->students_pages; $index++) { 
        if($index==$this->students_page){ ?>
        <span class="fc-f padlr6p bg-r3"><?php echo $index; ?></span>
        <?php }else{
       $url_array['up']=$index;
        ?>
    <a class="fc-f marlr6p" href="<?php echo $this->url($url_array); ?>"><?php echo $index; ?></a>
        <?php }
        } if ($this->students_page!=$this->students_pages){
    ?>
    <a class="fc-f marlr6p" href="<?php $url_array['up']=$this->students_page+1; echo $this->url($url_array); ?>" >&gt;&gt;</a>
    <?php
    } ?>
    </p>
</div>
<hr>
<?php }else{ ?>
<hr class="clf">
<?php }?>
*/ ?>

<?php 
$urls = array('action'=>'index');
foreach ($this->ad_sections as $k => $v) {
    if($v['page']>1 && $v['nr_per_page']<$v['count']){
        $urls[$k]=$v['page'];
    }
}
foreach ($this->ad_sections as $k => $data) { ?>
<h3><?php echo $data['section_name']; ?></h3>
<hr>
<?php foreach($data['ads'] as $ad): ?>
<?php if($ad['status'] != 0): ?>
<div class="ogloszenie h250p w27 fl p-r mar3 clearDeco oh fc-f">
    <a class="d-b wwbw w100 h100 p-a fc-f" href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>">
        <div class="padlr20p"><?php /* --- topic & content --- */ ?>
            <h4><?php 
                   echo $ad['topic']; ?></h4>
            <?php 
                   echo $ad['content']; ?>
        </div>
    </a>
    <div class="bg-r3 p-a b-100 fc-f w100 ad-panel an">
        <span class="d-ib pad10p fl">Autor: <?php echo strlen($ad['displayname'])>1 ? $ad['displayname'] : $ad['username']; ?></span>
        <span class="d-ib pad10p fl"><?php echo $ad['datetime'] ?></span><?php /* --- date --- */ ?>
    <?php if($this->identity): ?>
        <?php if($this->identity->user_id == $ad['author'] || $this->identity->role == 'admin'): ?>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" style="color:#000;" href="<?php echo $this->url(array('action' => 'edit', 'id' => $ad['ad_id'])) ?>">Edytuj</a>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" style="color:#000;" href="<?php echo $this->url(array('action' => 'delete', 'id' => $ad['ad_id'])) ?>">Usuń</a>
        <?php endif; ?>
    <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<?php endforeach; ?>
<?php if($data['nr_per_page']<$data['count']){ ?>
<div class="clf ta-c">
    <p class="padlr30p b3psr3 clearDeco d-ib bg-r3 fc-f fw-b">
    <?php 
    if ($data['page']!=1){
    ?>
        <a class="fc-f marlr6p" href="<?php $urls[$k]=$data['page']-1; echo $this->url($urls); ?>" >&lt;&lt;</a>
    <?php
    }
    for ($index = 1; $index <= $data['pages']; $index++) { 
        if($index==$data['page']){ ?>
        <span class="fc-f padlr6p bg-r3"><?php echo $index; ?></span>
        <?php 
        $current=$index;
        }else{
       $urls[$k]=$index;
        ?>
    <a class="fc-f marlr6p" href="<?php echo $this->url($urls); ?>"><?php echo $index; ?></a>
        <?php }
        } if ($data['page']!=$data['pages']){
    ?>
    <a class="fc-f marlr6p" href="<?php $urls[$k]=$data['page']+1; echo $this->url($urls); ?>" >&gt;&gt;</a>
    <?php
    } ?>
    </p>
</div>
<hr>
<?php }else{ ?>
<hr class="clf">
<?php }?>
<?php 
$urls[$k]=$current;
} ?>
<?php /*
 * ---- OLD SHIT IS OLD ---- stary layout indexu!!!! ----
<p class="lead" style="color: #3a87ad; text-decoration: underline">
    <strong>Najnowsze ogłoszenia</strong>
</p> 
<?php foreach($this->ads as $ad): ?>
<div class="br20 bg-c4 pad10p martb10p ">
    <div class="bg-c2 mar10p fs20p pad20p bs5 br20 fw-b">
        <a href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>"><?php echo $ad['topic'] ?></a>
    </div>
    <div class="pad20p mar10p  bg-c1 bs5 br10"> <!-- treść ogłoszenia -->
        <?php echo $ad['content'] ?>
    </div> 
    <div class="padlr20p bg-c2 mar10p br10"> <!-- data zamieszczenia-->
        <?php echo $ad['datetime'] ?>
    </div> 
    <!-- poniżej blok operacji -->
    <div class="mar10p">
        <a href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>">
            <button>Szczegóły</button>
        </a>
        <?php if($this->identity): ?>
        <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $ad['ad_id'])) ?>">
            <button>Edytuj</button>
        </a>
        <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $ad['ad_id'])) ?>">
            <button>Usuń</button>
        </a>
        <?php endif; ?>
    </div>
</div>
<?php endforeach; ?>

<?php if($this->identity): ?>
<a href="<?php echo $this->url(array('action' => 'createform'))?>">
    <button>Dodaj nowy rekord</button>
</a>
<?php endif; ?>
 */ ?>
