<?php $this->headTitle('Strona główna'); ?>
<?php /* --- bootstrap banner carousel --- */ ?>
<div id="carousel-wmi-captions" class="carousel slide h540p" data-ride="carousel">
  <!-- Indicators --><?php /* --- kropeczki, których Leszek nie chce ;) ---*/
  /*
  <ol class="carousel-indicators">
    <li data-target="#carousel-wmi-captions" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-wmi-captions" data-slide-to="1"></li>
    <li data-target="#carousel-wmi-captions" data-slide-to="2"></li>
  </ol>
*/ 
  ?>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
      <?php        foreach ($this->slideshow as $k => $s){ ?>
    <div class="item <?php if ($k==0) echo "active"; ?> bg-c<?php echo rand(1,6); ?>">
        <?php /* --- tło w postaci grafiki --- */ ?>
        <img class="" src="./img/overlay.png" alt="">
      <div class="carousel-caption h540p">
          <h1 class="mart120p"><?php echo $s['topic'] ?></h1>
          <h3><?php echo $s['content'] ?></h3>
      </div>
    </div>
      <?php } ?>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-wmi-captions" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-wmi-captions" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<?php /* --- carousel stop --- */ ?>
<?php /* --- layout indexu --- */ ?>
<hr>
<h3>Ogłoszenia pracowników</h3>
<hr>
<?php foreach($this->faculty_ads as $ad): ?>
<div class="h360p w40 fl p-r mar5 bgo clearDeco oh fc-f bg-c<?php echo rand(1,6); ?>">
    <a class="d-b w100 h100 p-a fc-f" href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>">
        <div class="padlr20p"><?php /* --- topic & content --- */ ?>
            <h4><?php echo $ad['topic'] ?></h4>
            <p><?php echo $ad['content'] ?></p>
        </div>
    </a>
    <div class="bg-r3 p-a b-100 fc-f w100 ad-panel an">
        <span class="d-ib pad10p fl"><?php echo $ad['datetime'] ?></span><?php /* --- date --- */ ?>
    <?php if($this->identity): ?><?php /* --- edit & delete--- */ ?>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" href="<?php echo $this->url(array('action' => 'edit', 'id' => $ad['ad_id'])) ?>">Edytuj</a>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" href="<?php echo $this->url(array('action' => 'delete', 'id' => $ad['ad_id'])) ?>">Usuń</a>
    <?php endif; ?>
    </div>
</div>
<?php endforeach; ?>
<hr class="clf">
<h3>Ogłoszenia studentów</h3>
<hr>
<?php foreach($this->students_ads as $ad): ?>
<div class="h360p w40 fl p-r mar5 bgo clearDeco oh fc-f bg-c<?php echo rand(1,6); ?>">
    <a class="d-b w100 h100 p-a fc-f" href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>">
        <div class="padlr20p"><?php /* --- topic & content --- */ ?>
            <h4><?php echo $ad['topic'] ?></h4>
            <p><?php echo $ad['content'] ?></p>
        </div>
    </a>
    <div class="bg-r3 p-a b-100 fc-f w100 ad-panel an">
        <span class="d-ib pad10p fl"><?php echo $ad['datetime'] ?></span><?php /* --- date --- */ ?>
    <?php if($this->identity): ?><?php /* --- edit & delete--- */ ?>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" href="<?php echo $this->url(array('action' => 'edit', 'id' => $ad['ad_id'])) ?>">Edytuj</a>
        <a class="fl b3psr3 padlr8p mar7p fc-f hbgr3" href="<?php echo $this->url(array('action' => 'delete', 'id' => $ad['ad_id'])) ?>">Usuń</a>
    <?php endif; ?>
    </div>
</div>
<?php endforeach; ?>
<hr class="clf">
<?php /*
 * ---- OLD SHIT IS OLD ---- stary layout indexu!!!! ----
<p class="lead" style="color: #3a87ad; text-decoration: underline">
    <strong>Najnowsze ogłoszenia</strong>
</p> 
<?php foreach($this->ads as $ad): ?>
<div class="br20 bg-c4 pad10p martb10p ">
    <div class="bg-c2 mar10p fs20p pad20p bs5 br20 fw-b">
        <a href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>"><?php echo $ad['topic'] ?></a>
    </div>
    <div class="pad20p mar10p  bg-c1 bs5 br10"> <!-- treść ogłoszenia -->
        <?php echo $ad['content'] ?>
    </div> 
    <div class="padlr20p bg-c2 mar10p br10"> <!-- data zamieszczenia-->
        <?php echo $ad['datetime'] ?>
    </div> 
    <!-- poniżej blok operacji -->
    <div class="mar10p">
        <a href="<?php echo $this->url(array('action' => 'show', 'id' => $ad['ad_id'])) ?>">
            <button>Szczegóły</button>
        </a>
        <?php if($this->identity): ?>
        <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $ad['ad_id'])) ?>">
            <button>Edytuj</button>
        </a>
        <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $ad['ad_id'])) ?>">
            <button>Usuń</button>
        </a>
        <?php endif; ?>
    </div>
</div>
<?php endforeach; ?>

<?php if($this->identity): ?>
<a href="<?php echo $this->url(array('action' => 'createform'))?>">
    <button>Dodaj nowy rekord</button>
</a>
<?php endif; ?>
 */ ?>