<br>
<p class="lead" style="color: #3a87ad; text-decoration: underline">
    <strong>Wyniki wyszukiwania</strong>
</p> 

<?php foreach ($this->search as $item): ?>
<?php if($item['status'] != 0): ?>
<div class="br20 bg-c4 pad10p martb10p ">
    <!-- Poniższe jest kompletnie nie przemyślane pod względem struktury treści strony. -->
<p class="bg-c2 mar10p fs20p pad20p bs5 br20 fw-b">Temat: <strong><?php echo $item['topic'] ?></strong></p>
<p class="pad20p mar10p  bg-c1 bs5 br10"><strong>Treść ogłoszenia:&nbsp;<br></strong><?php echo $item['content'] ?></p>
<p class="padlr20p bg-c2 mar10p br10"><strong>data utworzenia: <?php echo $item['datetime'] ?></strong></p>
<p class="padlr20p bg-c2 mar10p br10"><strong>autor: <?php echo $item['username'] ?></strong></p>
<p class="padlr20p bg-c2 mar10p br10">
    <strong>
        <?php 
        $now =  strtotime("now");
        $exp = strtotime($item['exp']);
        $result = $exp - $now;
        if ($result > 0)
        {
            echo $result . " sekund pozostało. status: " . $item['status'];
        }
        else
        {
            $result = 0;
            echo $result . " - koniec. status: " . $item['status'];
            $db = Zend_Db_Table::getDefaultAdapter();
            $item['status'] = 0;           
            $data = array(
                'status' => '0'
            );
            $where = $db->quoteInto('ad_id = ?', $item['ad_id']);
            $ads = new Application_Model_DbTable_Ads();
            $ads->update($data, $where); 
        }    
        ?>
    </strong>
</p>
<?php /* Przenoszę poniższe wyżej do treści ogłoszenia
<p><?php echo $this->object['content'] ?></p>
*/ ?>

<div class="mar10p">
    <a href="<?php echo $this->url(array('action' => 'index')) ?>">
        <button>Wstecz</button>
    </a>
    <?php if($this->identity): ?>
    <?php if($this->identity->user_id == $item['author']): ?>
    <a href="<?php echo $this->url(array('action' => 'edit')) ?>">
        <button>Edytuj</button>
    </a>
    <a href="<?php echo $this->url(array('action' => 'delete')) ?>">
        <button>Usuń</button>
    </a>
    <?php endif; ?>
    <?php endif; ?>
</div>
</div>
<?php else: ?>
    <p class="bg-c2 mar10p fs20p pad20p bs5 br20 fw-b"><strong>Szukane ogłoszenie już nie istnieje</strong></p>
<?php endif; ?>
<?php endforeach; ?>

