<br>
<p class="lead" style="color: #3a87ad; text-decoration: underline">
    <strong>Moje ogłoszenia</strong>
</p> 

<?php foreach ($this->ads as $item): ?>
<?php if ($item['status'] != 0): ?>
<div>
            <!-- CONTENT -->
 
            <div class="b-cont mar40p">

                <!-- POST TITLE -->
           
                <a href="<?php echo $this->url(array('action' => 'show', 'id' => $item['ad_id'])) ?>">
                    <h1 class="d-ib"><span class="d-b padl40p padr70p"><?php echo $item['topic'] ?></span>
                        <span class="d-b h3p bg-g2 marb4p"></span>
                        <span class="d-b h3p bg-g1 marr25p marb4p"></span>
                        <span class="d-b h3p bg-g2 marr50p marb4p"></span>
                    </h1>
                    </a>
                <!-- POST CONTENT -->
                <div class="padl40p">
                <?php if (strlen($item['content']) <=200){
                   echo $item['content'];
                }else {
                   echo $string2 = substr($item['content'], 0, 200);echo'(...)';} ?>
                
                </div>
                <span class="d-b h3p bg-g2 marb4p"></span>
                <div class="mar10p fr">

                    <?php if($this->identity): ?>
                         <!-- <//?php  if($this->view->identity->username == $item['author'] || $this->identity == 'admin'): ?>-->
                            <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['ad_id'])) ?>">
                                <button class="btn btn-success bg-g2">Edytuj</button>
                            </a>
                            <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['ad_id'])) ?>">
                                <button class="btn btn-danger">Usuń</button>
                            </a>
                        <!--<//?php endif; ?>-->
                    <?php endif; ?>
                    </div>
                <p class="padl40p">Autor: <?php echo $item['username'] ?></p>
                <p class="padl40p">Data dodania: <?php echo $item['datetime'] ?></p>
                <p class="padl40p">Data wygaśnięcia: <?php echo $item['exp'] ?></p>
            </div>
           
        <?php 
        $now =  strtotime("now");
        $exp = strtotime($item['exp']);
        $result = $exp - $now;
        /*if ($result > 0)
        {
            echo $result . " sekund pozostało. status: " . $item['status'];
        }*/
        if ($result <= 0)
        {
            $result = 0;
            //echo $result . " - koniec. status: " . $item['status'];
            $db = Zend_Db_Table::getDefaultAdapter();
            $item['status'] = 0;           
            $data = array(
                'status' => '0'
            );
            $where = $db->quoteInto('ad_id = ?', $item['ad_id']);
            $ads = new Application_Model_DbTable_Ads();
            $ads->update($data, $where); 
        }    
        ?>
    <!--</strong>
</p>-->
<?php /* Przenoszę poniższe wyżej do treści ogłoszenia
<p><?php echo $this->object['content'] ?></p>
*/ ?>
</div>
<?php //else: ?>
    <!--<p class="bg-c2 mar10p fs20p pad20p bs5 br20 fw-b"><strong>Ogłoszenie <?php //echo "\"" . $item['topic'] . "\"" ?> wygasło</strong></p>-->
<?php endif; ?>
<?php endforeach; ?>

