<br>
<p class="lead" style="color: #3a87ad; text-decoration: underline">
    <strong>Ogłoszenia studentów</strong>
</p> 

<?php foreach ($this->ads['ads'] as $item): ?>
<?php if ($item['status'] != 0): ?>
<div>
            <!-- CONTENT -->
 
            <div class="b-cont mar40p">

                <!-- POST TITLE -->
           
                <a href="<?php echo $this->url(array('action' => 'show', 'id' => $item['ad_id'])) ?>">
                    <h1 class="d-ib"><span class="d-b padl40p padr70p"><?php echo $item['topic'] ?></span>
                        <span class="d-b h3p bg-g2 marb4p"></span>
                        <span class="d-b h3p bg-g1 marr25p marb4p"></span>
                        <span class="d-b h3p bg-g2 marr50p marb4p"></span>
                    </h1>
                    </a>
                <!-- POST CONTENT -->
            
                <div class="padl40p">
                <?php if (strlen($item['content']) <=200){
                   echo $item['content'];
                }else {
                   echo $string2 = substr($item['content'], 0, 200);echo'(...)';
                } ?>
                </div>
                <span class="d-b h3p bg-g2 marb4p"></span>
                <div class="mar10p fr">

                    <?php if($this->identity): ?>
                        <?php if($this->identity->user_id == $item['author'] || $this->identity->role == 'admin'): ?>
                            <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['ad_id'])) ?>">
                                <button class="btn btn-success bg-g2">Edytuj</button>
                            </a>
                            <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['ad_id'])) ?>">
                                <button class="btn btn-danger">Usuń</button>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    </div>
                <p class="padl40p">Autor: <?php echo $item['username'] ?></p>
                <p class="padl40p">Data dodania: <?php echo $item['datetime'] ?></p>
                <p class="padl40p">Data wygaśnięcia: <?php echo $item['exp'] ?></p>
            </div>
     
        <?php 
        $now =  strtotime("now");
        $exp = strtotime($item['exp']);
        $result = $exp - $now;
        /*if ($result > 0)
        {
            echo $result . " sekund pozostało. status: " . $item['status'];
        }*/
        if ($result <= 0)
        {
            $result = 0;
            //echo $result . " - koniec. status: " . $item['status'];
            $db = Zend_Db_Table::getDefaultAdapter();
            $item['status'] = 0;           
            $data = array(
                'status' => '0'
            );
            $where = $db->quoteInto('ad_id = ?', $item['ad_id']);
            $ads = new Application_Model_DbTable_Ads();
            $ads->update($data, $where); 
        }    
        ?>
    <!--</strong>
</p>-->
<?php /* Przenoszę poniższe wyżej do treści ogłoszenia
<p><?php echo $this->object['content'] ?></p>
*/ ?>
</div>
<?php endif; ?>
<?php endforeach;
$data = $this->ads;
$base = array('controller'=>'index','action'=>'showstudentads');
if($data['nr_per_page']<$data['count']){ ?>
<div class="clf ta-c">
    <p class="padlr30p b3psr3 clearDeco d-ib bg-r3 fc-f fw-b">
    <?php 
    if ($data['page']!=1){
    ?>
        <a class="fc-f marlr6p" href="<?php echo $this->url($base,null,true).'/page/'.($data['page']-1); ?>" >&lt;&lt;</a>
    <?php
    }
    for ($index = 1; $index <= $data['pages']; $index++) { 
        if($index==$data['page']){ ?>
        <span class="fc-f padlr6p bg-r3"><?php echo $index; ?></span>
        <?php }else{
        ?>
    <a class="fc-f marlr6p" href="<?php echo $this->url($base,null,true).'/page/'.$index; ?>"><?php echo $index; ?></a>
        <?php }
        } if ($data['page']!=$data['pages']){
    ?>
    <a class="fc-f marlr6p" href="<?php echo $this->url($base,null,true).'/page/'.($data['page']+1); ?>" >&gt;&gt;</a>
    <?php
    } ?>
    </p>
</div>
<hr>
<?php }

