<br>
<p class="lead" style="color: #3a87ad; text-decoration: underline">
    <strong>Ogłoszenia studentów</strong>
</p> 

<?php foreach ($this->ads as $item): ?>
<?php if ($item['status'] != 0): ?>
<div class="">
     <!-- CONTENT -->
 
            <div class="b-cont mar40p">

                <!-- POST TITLE -->
           
                <h1 class="d-ib"><span class="d-b padr70p"><?php echo $item['topic'] ?></span>
                    <span class="d-b h3p bg-g2 marb4p"></span>
                    <span class="d-b h3p bg-g1 marr25p marb4p"></span>
                    <span class="d-b h3p bg-g2 marr50p marb4p"></span>
                </h1>
                <!-- POST CONTENT -->

                <p class=""><?php echo $item['content'] ?> </p>
                <span class="d-b h3p bg-g2 marb4p"></span>
                <p class="">Autor:<?php echo $item['username'] ?></p>
                <p class=""><?php echo $item['datetime'] ?></p>
            </div>
     
        <?php 
        $now =  strtotime("now");
        $exp = strtotime($item['exp']);
        $result = $exp - $now;
        /*if ($result > 0)
        {
            echo $result . " sekund pozostało. status: " . $item['status'];
        }*/
        if ($result <= 0)
        {
            $result = 0;
            //echo $result . " - koniec. status: " . $item['status'];
            $db = Zend_Db_Table::getDefaultAdapter();
            $item['status'] = 0;           
            $data = array(
                'status' => '0'
            );
            $where = $db->quoteInto('ad_id = ?', $item['ad_id']);
            $ads = new Application_Model_DbTable_Ads();
            $ads->update($data, $where); 
        }    
        ?>
    <!--</strong>
</p>-->
<?php /* Przenoszę poniższe wyżej do treści ogłoszenia
<p><?php echo $this->object['content'] ?></p>
*/ ?>

<div class="mar10p">
    <?php if($this->identity): ?>
    <?php if($this->identity->user_id == $item['author'] || $this->identity->role == 'admin'): ?>
    <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['ad_id'])) ?>">
        <button>Edytuj</button>
    </a>
    <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['ad_id'])) ?>">
        <button>Usuń</button>
    </a>
    <?php endif; ?>
    <?php endif; ?>
</div>
</div>
<?php endif; ?>
<?php endforeach; ?>

