<?php echo $this->doctype(); ?>

<html>
    <head>
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headScript();
        ?>
    </head>
    
    <body>
        <div class="container">
            <header id="header">
                <div id="top">
                    <div class="container"></div>
                </div>
                <div id="pattern">
                    <div id="logo">
                    </div>
                </div>
            </header>
            <div id="search"></div>
            <?php echo $this->layout()->content; ?> 
            <footer id="footer"></footer>
        </div>
    </body>
</html>